name: "flan-t5-small"
backend: "python"

input [
  {
    name: "schema"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]
input [
  {
    name: "user_query"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]

output [
  {
    name: "generated_ql"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]

instance_group [
  {
    kind: KIND_CPU
  }
]