name: Publish Docker image

on:
  push:
    branches:
      - main
      - dev

jobs:

  push_to_registry_serving:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: kyrylprojector/serving:latest
          target: serving
          cache-from: type=registry,ref=kyrylprojector/serving:buildcache
          cache-to: type=registry,ref=kyrylprojector/serving:buildcache,mode=max

  push_to_registry_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: kyrylprojector/pipeline:latest
          target: pipeline
          cache-from: type=registry,ref=kyrylprojector/pipeline:buildcache
          cache-to: type=registry,ref=kyrylprojector/pipeline:buildcache,mode=max

  push_to_registry_monitoring:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: kyrylprojector/monitoring:latest
          target: monitoring
          cache-from: type=registry,ref=kyrylprojector/monitoring:buildcache
          cache-to: type=registry,ref=kyrylprojector/monitoring:buildcache,mode=max
